const constantsText = {
  website: 'Website',
  email: 'Email',
  password: 'Password',
  login: 'Login',
  forgotPassword: 'Forgot Password?',
  forgotPasswordTitle: 'PASSWORD',
  shoppin: 'SHOPPIN',
  Change_Password: 'Change Password',
  Dashboard: 'Dashboard',
  home: 'Home',
  orders: 'Orders',
  products: 'Products',
  settings: 'Settings',
  search: 'Search',
  totalSale: 'Total Sales',
  collections: 'Collections',
  order_details: 'Order Details',
  order: 'Order #',
  orderDate: 'Order Date',
  customer: 'Customer',
  shippingAddressText: 'Shipping Address',
  shippingAddress: '5051 prear Road Vamcovver BC V4Z 1J6 Canada',
  billingAddressText: 'Billing Address',
  contact: 'Contact',
  emailID: 'johnedoe@emample.com',
  title: 'Title',
  estimate_delivery_date: 'Estimate delivery date',
  delivery_date_unavailable: 'Delivery Date Unavailable',
  tracking_number: 'Tracking number',
  tracking_number_text: 'LK4XXXXX334XHK',
  orderSummadry: 'Order Summary',
  sub_total_text: 'Subtotal',
  sub_total: 'US$186.40',
  shipping_charge_text: 'Shipping (UPS One Day)',
  shipping_charge: 'US$8.30',
  total_text: 'Total',
  total: 'U$194.70',
  note: 'Note',
  note_content: 'Free Shipping is possible \nPlease Put Value at lesser amount of to avoid\ncustomer duties and taxes',
  month: 'About 2 month',
  address: 'Vancouver BC, Canada',
  recenOrders: 'Recent Orders',
  address1: 'address 1',
  address2: 'address 2',
  address3: 'City State Zipcode\nCountry',
  title_of_list: 'The Xirius Swarovski Crystal 2088',
  no_of_orders: '3 Orders',
  date: '2 Mar',
  lastOrder: 'Last Order',
  app_setings: 'App Settings',
  pushNotifications: 'Push Notifications',
  badgeAppIcon: 'Badge App Icon',
  logOut: 'Log out',
  product_price: 'US$0.00',
  today: 'Today',
  yesterday: 'Yesterday',
  this_week: 'This Week',
};
export default constantsText;
