import { Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const standardFormat = {
  marginVertical: height / 50,
  marginHorizontal: width / 40,
  inputWidth: width / 1.5,
  buttonWidth: width / 50,
  headerMarginTop: width / 3,
  marginLeft: width / 20,
  searchWidth: width / 1.1,
  buttomMarginTop: height / 20,
  inputMarginTop: height / 15,
  marginTop: height / 20,
  forgotButtonWidth: width / 1.3,
  topMargin: height / 20,
  orderImageWidth: width / 1.2,
  width,
  padding: width / 15,
  productImage: height / 2.5,
  productImageView: height / 3,
  top_margin: height / 6,
  topSpace: height / 50,
  forgot_password_margin: height / 30,
  listMargin: height / 35,
  list_margin: height / 50,
  arrow_top_margin: height / 25,
  setting_top_margin: height / 60,
  image_slider_padding: width / 30,
  imageSlider_margin_horizontal: width / 5,
  background_height: height,
  logo_place: height / 5.5,
  logo_textplace: height / 50,
  regular: '500',
  medium: '700',
  button_height: height / 20,
  logo_size: height / 13,
  header_footer_size: height / 10,
  footer_text_margin: height / 150,
  circle_image: height / 20,
  circle_image_radius: height / 40,
  slider_height: height / 8,
  switch_height: height / 10,
  footer_padding: height / 100,
  padding_search_view: height / 120,
  extra_margin_top: height / 40,
  border_slider_view: height / 20,
};

export default standardFormat;
